### PR TITLE
Increase freedesktop expire timeout

### PR DESCRIPTION
**Pull request by dawidd6**
#### Description
Increases 500ms freedesktop expire timeout to 5s.

#### Resolves
Notification was visible way too short.

### CODE REVIEW

**Comment by teto** [comment]
oh I now understand why I had no time to read the notification xD LGTM !

**Comment by MartinPotier** [comment]
Yeah this is pretty much unusable with linux desktop notification. Not time to read in 0.5s…

**Comment by teto** [comment]
there doesn't seem to be too much activity on this repo. Do you guys still use noti or could you recommand something similar for linux (FOSS) ?

**Comment by variadico** [comment]
Thanks! Sorry for the late response!

**Pull request merged**
