### PR TITLE
Add BearyChat

### PR DESCRIPTION
**Pull request by bcho**
#### Description

This pull request implements support for [BearyChat][bc] notification. It requires `NOTI_BC_INCOMING_URI` envvar.

[bc]: https://github.com/integrations/bearychat

#### Resolves

Add a new notification.

### CODE REVIEW

**Comment by bcho** [comment]
Notification looks like this.

**Comment by variadico** [comment]
Sweet.

Do you have any wisdom about BearyChat that can be recorded here: https://github.com/variadico/noti/blob/master/docs/noti.md?

**Comment by bcho** [comment]
@variadico patch updated!

**Comment by variadico** [comment]
Nice! This is really great! 

There's one teeny problem though. Could you reopen this against dev instead of master? 🙏

**Comment by bcho** [comment]
ha, that's on me! Merge base changed!

**Comment by variadico** [comment]
Awesome! Thank you very much! I'll cut a new release in the coming days. 🎉

**Comment by bcho** [comment]
cool！

**Pull request merged**
