### PR TITLE
preliminary unix support (fixes #3 )

### LINKED ISSUE #3: Support for Linux?
Linux uses a notify-send tool to send similar kind of notifications, I'd love to send a PR, will you be open to merge it?

### PR DESCRIPTION
**Pull request by cryptix**
Hey,

I just pulled `func notify()` out and put them into `_darwin.go` and added my call to `notify-send` from [tnse](https://github.com/cryptix/cmd/tree/master/tnse) in `_unix.go` using `// +build linux freebsd` which is where I tested this myself.

resolves #3

### CODE REVIEW

**Comment by variadico** [comment]
Neat! I'll try to really look at this during the weekend. :+1:

**Comment by variadico** [comment]
I tested this under:
* Ubuntu 14.04.3
* notify-send 0.7.6

Everything checks out.

For doc purposes, what environment did you test this in?

**Comment by thewhitetulip** [comment]
damn, I also hacked the code for supporting to linux https://github.com/variadico/noti/pull/5, hadn't seen that this PR had already been submitted :smile:

**Comment by cryptix** [comment]
Hey,

I tested this under:

* FreeBSD 10.2-RELEASE-p7
* notify-send 0.7.6
* using [dunst](http://knopwob.org/dunst/index.html) 1.1.0

and

* Linux Mint  17.2
* notify-send 0.7.6

I'll send a commit with updated docu shortly.

**Comment by cryptix** [comment]
@variadico: Pushed 737e0b1. Feel free to scratch the 2nd added screenshot.

**Comment by variadico** [comment]
@thewhitetulip Yeah... Sorry! Thanks for playing! Have a cookie. :cookie:

**Comment by thewhitetulip** [comment]
@variadico hahaha thanks!

**Comment by variadico** [comment]
LGTM! Thanks, @cryptix!

**Comment by cryptix** [comment]
Cheers! :+1:

**Pull request merged**
