### PR TITLE
Add simplepush

### PR DESCRIPTION
**Pull request by tymm**
Please take into consideration that I never coded in go lang before.

Since I didn't know how to run the tests `simplepush/simplepush_test.go` is not tested.
Everything else seems to work.

### CODE REVIEW

**Comment by variadico** [comment]
Will take a look this weekend. Thanks!

**Comment by variadico** [comment]
> Since I didn't know how to run the tests 

```
cd simplepush
go test
```
That's how you run tests. Looks like you got an error.

```
--- FAIL: TestEnvConfig (0.00s)
	simplepush_test.go:48: 0 unexpected configuration
	simplepush_test.go:49:  got: {fu }
	simplepush_test.go:50: want: { }
```

Is that a real failure?

**Comment by tymm** [comment]
I was confused about `env` and `config` in `TestEnvConfig`.
Now everything should be correct. 

Please see the updated version.

**Comment by variadico** [comment]
LGTM! 🎉 
I'll cut a new release of `noti` with Simplepush support soon! Thank you very much!!!

**Pull request merged**
