### PR TITLE
added option to not send notify-send for cluster use

### PR DESCRIPTION
**Pull request by gedankenstuecke**

### CODE REVIEW

**Comment by variadico** [comment]
Soo... What is this about? Why do we need this? What's the use case you're trying to solve?

**Comment by gedankenstuecke** [comment]
Sorry for being not more specific. So, my use case is that I'm running lots of long-running computations on a cluster consisting of regular workstations I'm using and dedicated compute nodes. So some of the nodes do have X11/notify-send installed, others don't . 

I'd like to be able to use noti on my laptop/workstations and the headless compute-nodes to at least notify me on my phone etc. using pushbullet in those cases where no GUI is available. So by adding additional parameter you can run noti as Pushbullet front-end for those cases. 

I guess you could just use a dedicated pushbullet-CLI-client for the non-X11-cases, but by adding the parameter to noti you only have to remember the syntax for one tool and only setup & maintain one tool.

**Comment by variadico** [comment]
Ooooooohhhh. Okay. This makes perfect sense now. I ran into this case myself a few months ago. 

I use OS X most of the time, so I hadn't noticed that the Linux version of `noti` always used `notify-send`. You might be interested in the [dev branch] of `noti`, which will become version 2 soon. In v2, you can set the default notification type through an environment variable. (Also added Slack notifications.)

For example, this is what my `.bashrc` looks like on one of my backup servers.
```
export NOTI_DEFAULT="slack"
export NOTI_SLACK_TOK='secret-token'
export NOTI_SLACK_DEST='@variadico'
```
Then, I just run `noti backup_server.sh` and I'll always get Slack notifications on my desktop and phone. This is effectively the headless mode you were looking for.

[dev branch]: https://github.com/variadico/noti/tree/dev

**Comment by gedankenstuecke** [comment]
Ah, yes, v2 seems to do just that, with the option to disable the banner notifications. So I guess we could just go for -b in this release and have this already present for people who are waiting for the v2 :-)

**Comment by variadico** [comment]
Just released v2 a few minutes ago! :D You can update! :tada:

**Comment by gedankenstuecke** [comment]
:+1:

**Pull request closed without merging**
