### PR TITLE
Twilio integration #124

### PR DESCRIPTION
**Pull request by naormalca**
[Twilio](https://www.twilio.com/messaging) is a cloud provider that allows sending SMS via API.

### CODE REVIEW

**Comment by naormalca** [comment]
I'm not sure why the macOS build is failed, something that related to the version tests.
```
--- FAIL: TestNoti (4.79s)
    --- FAIL: TestNoti/show_version (0.74s)
```

@variadico can you look on this?

**Comment by variadico** [comment]
Awesome, thanks! Will review soon! :bow:

**Comment by variadico** [comment]
Awesome, we're 99% there!

Is there anything you can add to this section?
https://github.com/variadico/noti/blob/master/docs/noti.md#setting-up-cloud-accounts

Any notes on how to get AuthToken or accountSid or numberTo?

**Comment by naormalca** [comment]
Oh i missed that section, tomorrow it will be ready.

**Comment by variadico** [comment]
Awesome, thanks! LGTM!

**Pull request merged**
